# Generated by Django 5.1.3 on 2024-11-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='examen_tiene_ramas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.examen')),
                ('idRama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.materia')),
            ],
        ),
        migrations.CreateModel(
            name='examen_tiene_materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idExamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.examen')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.materia')),
            ],
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('idRama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.materia')),
            ],
        ),
        migrations.CreateModel(
            name='rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.materia')),
            ],
        ),
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('esCorrecta', models.BooleanField(default=False)),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.pregunta')),
            ],
        ),
    ]
