# Generated by Django 5.1.3 on 2024-11-08 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen_tiene_ramas',
            name='idExamen',
        ),
        migrations.RemoveField(
            model_name='examen_tiene_ramas',
            name='idRama',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='examen',
            name='idMateria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina_web.materia'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='idExamen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina_web.examen'),
        ),
        migrations.DeleteModel(
            name='examen_tiene_materias',
        ),
        migrations.DeleteModel(
            name='examen_tiene_ramas',
        ),
    ]
