# Generated by Django 5.1.3 on 2024-11-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0002_remove_examen_tiene_ramas_idexamen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='idRama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.rama'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
