# Generated by Django 5.1.3 on 2024-11-22 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0003_alter_pregunta_descripcion_alter_pregunta_idrama_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(default='PENDIENTE', max_length=20)),
                ('resultado', models.FloatField(default=0)),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina_web.alumno')),
                ('idExamen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina_web.examen')),
            ],
        ),
    ]
