# Generated by Django 5.1.3 on 2024-11-22 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0004_alumno_idusuario_intento'),
    ]

    operations = [
        migrations.CreateModel(
            name='avances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina_web.alumno')),
                ('idIntento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina_web.intento')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pagina_web.pregunta')),
                ('idRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina_web.respuesta')),
            ],
        ),
    ]
